navn = input("kva er navne dit")
alder = input("ka er alderen din")
adres = input("ka er adresa din")
postnomer = input("ka er postnomer")
sted = input ("kor bur du")

print("navn")
print("alder")
print("adres")
print("postnomer")
print("sted")
print("hei",navn,"wow du er",alder,"år gamal du er nesten dø")
print("hei",navn,"eg veit at adreso din er",adres,"og at postnomeret dit er",postnomer,"og du bur i",sted,"christer suge")
alder1 =input("kor gamald er du")
hundre = 100 - int(alder1)
print("du er 100 omm",hundre,"år")